# Site settings
title: Unsorted Ideas
email: 
description: "Commentaries on tech, science and life"
baseurl: ""
url: "http://sudhirkk.github.io"
twitter_username: sudhirkk
github_username:  sudhirkk

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
